name: Publish Packages
env:
  CI: true

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      dist_tag:
        description: 'Distribution Tag'
        type: choice
        options:
          - 'next'
          - 'latest'
          - 'rc'
          - 'dev'
          - 'alpha'
          - 'beta'
        required: true
        default: 'dev'
      release_branch:
        description: 'Release Branch'
        type: choice
        options:
          - 'next'
          - 'master'
        required: true
        default: 'next'
      strategy:
        description: 'Release Strategy'
        type: choice
        options:
          - 'from-git'
          - 'from-package'
        required: true
        default: 'from-package'
      target_branch:
        description: 'Target branch to release from'
        type: choice
        options:
          - 'next'
          - 'master'
        required: true
        default: 'next'
jobs:
  publish:
    name: Publish Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}

      - name: Setup Registry
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          scope: '@contractual'
          always-auth: true

      - name: NPM
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish Packages
        run: npx lerna publish ${{ github.event.inputs.strategy }} --yes --dist-tag ${{ github.event.inputs.dist_tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
